### PR TITLE
Feature/data definition patching fixes

### LINKED ISSUE #8: Patch executed multiple times
Hi,

I created simple patch:
```yaml
Race:
  - update-all:
      $where: def.RaceId >= 0 and def.RaceId < 8
      Bonuses:
        - Type: CounterEspionage
          Amount: value + 0.1
```

From debug log it seems it is executed 3 times and as result ex. Zenox race selection page show 40% Counter Espionage bonus (expected is 20%, from 10% original bonus).

Is it a bug or some problem in patch file?
From Debug console log it seems it is updating 2x at game start and then another 1x time when selecting start new game button.

BTW. Thanks for great work!

### PR DESCRIPTION
**Pull request by froce**
Fixes #8 (multiple patch execution)

Adds reflection as a fallback to detect "indexed" lists which don't inherit from IndexedList<T>.

Caches patched static definitions between runs, to avoid slow patching.

### CODE REVIEW

File: DistantWorlds2.ModLoader.ModManager/ModManager.cs [hunk 1]
```diff
@@ -327,22 +332,29 @@ public class ModManager : IModManager {
...
 
-    _loadOrder = Mods.Values.Where(m => m.IsValid)
+    _loadOrder = Mods.Values.Where(m => m.IsValid)      
       .OrderByDescending(m => m.LoadPriority)
+      .ThenByDescending(m => m.Name)
       .StableOrderTopologicallyBy(ModInfo.GetResolvedDependencies);
 
     AppDomain.CurrentDomain.AssemblyResolve += ModAssemblyResolver;
+        
+    Crc64 checksumHasher = new Crc64(); //XxHash returns same results for different input?!?
```
Comment (TYoungSL) [inline DistantWorlds2.ModLoader.ModManager/ModManager.cs:342]: If it returns different results for same input, it'd be broken.

If it returns same results for different input, _probably_ the input is broken.

Comment (TYoung86) [reply DistantWorlds2.ModLoader.ModManager/ModManager.cs:342]: https://github.com/dotnet/runtime/issues/69184

File: DistantWorlds2.ModLoader.Core/GameDataDefinitionPatching.cs [hunk 2]
```diff
@@ -136,17 +161,213 @@ public static class GameDataDefinitionPatching
...
+                    Console.Error.WriteLine($"Failure applying content patches from {dataPath}");
+                    ModLoader.ModManager.OnUnhandledException(ExceptionDispatchInfo.Capture(ex));
+                }
+            }
+            ModLoader.ModManager.CachedDefinitions = new Dictionary<string, object>(); ;
+            foreach (var (_, name) in StaticDefNames)
+            {                
+                MemberInfo mi = typeof(Galaxy).GetMember(name, BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public).First();
+                ModLoader.ModManager.CachedDefinitions[name] = GetValue(null, mi)!;
+            }
```
Comment (TYoung86) [inline DistantWorlds2.ModLoader.Core/GameDataDefinitionPatching.cs:221]: use StaticDefs to get field value instead

Comment (Tyler-IN) [inline DistantWorlds2.ModLoader.Core/GameDataDefinitionPatching.cs:221]: Use StaticDefs to get field value

File: DistantWorlds2.ModLoader.ModManager/ModManager.cs [hunk 3]
```diff
@@ -613,6 +616,31 @@ private static void HideMessageDialog(object o, DWEventArgs dwEventArgs)
 
   public ConcurrentDictionary<string, object> SharedVariables { get; } = new();
 
+  private byte[] CalculateGameDataChecksum()
+  {
+    var checksumHasher = new Crc64(); //TODO: Switch back to XxHash64 once https://github.com/dotnet/runtime/issues/69184 is resolved and released.
```
Comment (Tyler-IN) [inline DistantWorlds2.ModLoader.ModManager/ModManager.cs:621]:
```suggestion
    var checksumHasher = ModInfo.GetHasher();
```

N.B.

Comment (Tyler-IN) [reply DistantWorlds2.ModLoader.ModManager/ModManager.cs:621]: Might move ModInfo.Hasher / GetHasher to ModManager or somewhere higher in the load order?

File: DistantWorlds2.ModLoader.ModManager/ModManager.cs [hunk 4]
```diff
@@ -30,16 +31,15 @@ public class ModManager : IModManager {
 
   private string? _modsDir;
 
+  private byte[]? _checksum;
```
Comment (Tyler-IN) [inline DistantWorlds2.ModLoader.ModManager/ModManager.cs:34]:
```suggestion
  // Game data checksum
  private byte[]? _checksum;
```
or ...
```suggestion
  private byte[]? _gameDataChecksum;
```
(would require refactoring usages)

N.B.

File: DistantWorlds2.ModLoader.ModManager/ModManager.cs [hunk 5]
```diff
@@ -613,6 +616,31 @@ private static void HideMessageDialog(object o, DWEventArgs dwEventArgs)
...
+      foreach (var mod in _loadOrder)
+      {
+        checksumHasher.Append(mod.Hash);
+      }
+    }
+
+    return checksumHasher.GetCurrentHash();
+  }
+
+  public string Checksum {
```
Comment (Tyler-IN) [inline DistantWorlds2.ModLoader.ModManager/ModManager.cs:638]:
```suggestion
  // Game data / version / state checksum
  public string Checksum {
```
or...
```suggestion
  public string GameDataChecksum {
```
(would require refactoring)

N.B.

File: DistantWorlds2.ModLoader.Core/GameDataDefinitionPatching.cs [hunk 6]
```diff
@@ -136,17 +146,148 @@ public static class GameDataDefinitionPatching
...
+                .CompileFast());
+
+            IsIndexedListCache[list.GetType()] = true;
+            return true;
+        }
+        else
+        {
+            IsIndexedListCache[list.GetType()] = false;
+            return false;
+        }
```
Comment (Tyler-IN) [inline DistantWorlds2.ModLoader.Core/GameDataDefinitionPatching.cs:194]: Can reduce 6 code instances of `list.GetType()` to a local var.
If `T` is the final type can use `typeof(T)` instead of `list.GetType()`.


N.B.

File: DistantWorlds2.ModLoader.Core/GameDataDefinitionPatching.cs [hunk 7]
```diff
@@ -1164,6 +1376,32 @@ object ConvertToIdType(object id)
...
+            bool ContainsId(List<T> defs, object id)
+            {
+                switch (defs)
+                {
+                    case IndexedList<T> indexed:
+                        return indexed.ContainsId(ConvertToInt(id));
+
+                    default:
+                        MethodInfo mi = defs.GetType().GetMethod("ContainsId");
+                        return (bool)mi.Invoke(defs, new object[] { id });
```
Comment (Tyler-IN) [inline DistantWorlds2.ModLoader.Core/GameDataDefinitionPatching.cs:1401]: how often is this called? for every item in a collection potentially, multiple times in multiple loops?

File: DistantWorlds2.ModLoader.Core/IModManager.cs [hunk 8]
```diff
@@ -20,6 +20,8 @@ public interface IModManager
 
     ConcurrentDictionary<string, object> SharedVariables { get; }
 
+    public string Checksum { get; }
```
Comment (Tyler-IN) [inline DistantWorlds2.ModLoader.Core/IModManager.cs:23]:
```suggestion
    // Game data checksum
    public string Checksum { get; }
```
or...
```suggestion
    public string GameDataChecksum { get; }
```
(would require refactoring)

N.B.

**Review by Tyler-IN — COMMENTED** [review]
All the comments marked N.B. for non-blocking don't need to be fully addressed in the PR before being merged, can be addressed later.

File: .gitignore [hunk 9]
```diff
@@ -7,3 +7,4 @@ riderModule.iml
 .vs
 *.snk
 launchSettings.json
+.editorconfig
```
[the remark this answers is not in the document]
Comment (froce) [reply .gitignore:10]: If you have an .editorconfig for the project please add it. Mine was auto-generated, but is not actually a full match for the existing code.

File: DistantWorlds2.ModLoader.ModManager/ModManager.cs (hunk 3 above)
Comment (Tyler-IN) [reply DistantWorlds2.ModLoader.ModManager/ModManager.cs:621]: GetHasher is a static factory method. It will give you a new object I think.
